### ISSUE TITLE
Mods are outdated

### ISSUE THREAD

**Issue by eyerockk** [Livku/Gorilla-Tag-Mods#2]
I have tested most of these and none of them work because of the 1.1.15 update. Do you know any that work with the new update?

**Comment by Crazby** [comment]
CI broke because of the big update and imagine using public mods

**Comment by Livku** [comment]
If You Paying Any Attention, You Would Have Both Seen What I Wrote On The ReadMe. 
NO MORE CHEATS, I Only Put Cheats There To Store It, And Didn't Expect Everyone To Fork It Abd Use It.
I WON'T BE UPDATING THIS ANYMORE
